### ISSUE TITLE
Consider swapping order of formula, data args of plotluck for easier piping

### ISSUE THREAD

**Issue by richierocks** [stefan-schroedl/plotluck#1]
I realise that having `fn(formula, data)` is traditional, and follows the pattern of many functions in the `stats` and `lattice` packages.

However, many modern packages use `data` as the first argument (notably `ggplot2` and the tidyverse packages).  This makes it easier to pipe commands using `magrittr`.  For example, I can do

``` r
iris %>%
  ggplot(aes(Petal.Length, Species)) + 
  geom_point()
```

Since the data argument isn't first, piping isn't as clean with `plotluck`.

It would be really useful if you could either
1. swap the order of `formula` and `data` arguments in the `plotluck` function, or
2. if you don't want to break backwards compatibility, introduce a new function (`luckplot`?) which does the same thing but has the arguments reversed.

**Comment by stefan-schroedl** [comment]
Hi Richard,

thank you for the suggestion! Makes sense to me, I will consider it in the next release.

- Stefan
